baseURL: "https://matthewdaunt.me" 
title: Matt Daunt's Homepage
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Personal
          url: personal/
          weight: 3
        - name: Resume
          url: Matthew_Daunt_Resume_2025.pdf
          weight: 4

params:
    description: "I am a PhD candidate in astrophysics at New York University, nearing dissertation defense. My research focuses on precision measurements of stellar radial velocities using data-driven methods. I enjoy teaching laboratory sessions and guiding students through hands-on exploration of physical concepts. In my personal time, I pursue coding projects in image processing, building custom filters and blending algorithms that complement my computational approach to astrophysical research."
    author: Matthew Daunt
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","courses","personal","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Matthew Daunt
          subtitle: "I am a PhD candidate in astrophysics at New York University, nearing dissertation defense. My research focuses on precision measurements of stellar radial velocities using data-driven methods. I enjoy teaching laboratory sessions and guiding students through hands-on exploration of physical concepts. In my personal time, I pursue coding projects in image processing, building custom filters and blending algorithms that complement my computational approach to astrophysical research."
          imageUrl: "IMG_1144.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Personal
              url: personal/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Resume
          url: Matthew_Daunt_Resume.pdf
        - name: GitHub
          url: https://github.com/mdd423
        # - name: Twitter
        #   url: https://x.com/dattmaunt

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Matt Daunt"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2